language: python
python:
  - 2.6
  - 2.7
before_install: 
  - pip install -r requirements-dev.txt --use-mirrors
script: 
  - python setup.py test
  - coverage run setup.py test
  - coverage report -m
